/**
 * Orb fixture pet presentation (DSH_PET_OVERLAY_ADAPTER_V8 §17): the bundled
 * third-pet fixture — a completely different visual identity and its own
 * journey pack (`orb-fixture`), addable exactly like any creator pet:
 * configuration, assets, copy, and license metadata only. The pose assets and
 * their generated module come from the deterministic local pipeline
 * (`scripts/generate-orb-fixture-assets.mjs`, see PROVENANCE-orb.json).
 */

import { orbAssets, orbPoseAlphaBounds, orbVariantPose } from './orb-assets.generated'
import orbSpeech from './speech.json' with { type: 'json' }
import orbLevels from './levels.json' with { type: 'json' }
import type { PetPresentation, PetSpeechCatalogData, PoseSpriteRecipeData } from '../types'
import type { VehiclePetExpressionVariant } from '../../expressions'

const poseSprite: PoseSpriteRecipeData = {
  variantPose: orbVariantPose as Record<VehiclePetExpressionVariant, number>,
  poses: orbAssets,
  alphaBounds: orbPoseAlphaBounds,
  insignia: undefined,
}

/** V8 DEC-OVERLAY-029 default public experience: pet first; details in the Full Journey. */
const gradePolicy = {
  showExactLevelNumber: false,
  showDescription: false,
  insigniaMode: 'none',
} as const

const behavior = {
  ambientPool: ['rest', 'look-around', 'look-left', 'look-right'],
  stateReactions: { completed: 'nod', failed: 'shy', working: 'nod', 'needs-input': 'peek' },
  petting: { variant: 'idle-happy', decoration: 'sparkles' },
} as const satisfies PetPresentation['behavior']

export const orbPresentation: PetPresentation = {
  id: 'orb',
  displayName: { 'zh-CN': '光球', en: 'Orb' },
  recipe: 'pose-sprite',
  packId: 'orb-fixture',
  userSelectable: true,
  gradePolicy,
  gradeLevels: orbLevels,
  behavior,
  speech: orbSpeech as PetSpeechCatalogData,
  license: {
    license: 'SEE REPOSITORY LICENSE GATE (docs/public/ASSET_AND_BRAND_POLICY.md)',
    attribution: 'Original fixture art generated by the in-repo deterministic pipeline.',
    provenance: 'src/dsh/client/pets/orb/PROVENANCE-orb.json',
  },
  poseSprite,
}

