/**
 * GENERATED FILE — do not edit. Run `node scripts/generate-pet-wiring.mjs`.
 * Wiring for pet 'orb', emitted from pet.json + levels.json +
 * speech.json + scanned asset files only (V8 CTR-038; the data files are
 * the source of truth and this module is tool output).
 */

import p0 from './assets/pose-0.png'
import p1 from './assets/pose-1.png'
import p2 from './assets/pose-2.png'
import p3 from './assets/pose-3.png'
import p4 from './assets/pose-4.png'
import p5 from './assets/pose-5.png'
import p6 from './assets/pose-6.png'
import p7 from './assets/pose-7.png'
import p8 from './assets/pose-8.png'
import p9 from './assets/pose-9.png'
import w0 from './assets/pose-0.webp'
import w1 from './assets/pose-1.webp'
import w2 from './assets/pose-2.webp'
import w3 from './assets/pose-3.webp'
import w4 from './assets/pose-4.webp'
import w5 from './assets/pose-5.webp'
import w6 from './assets/pose-6.webp'
import w7 from './assets/pose-7.webp'
import w8 from './assets/pose-8.webp'
import w9 from './assets/pose-9.webp'
const alphaBounds = [[50,150,270,350],[50,150,270,350],[50,150,270,350],[50,150,270,350],[37,150,283,350],[50,147,270,350],[31,121,289,379],[50,150,270,350],[50,150,270,371],[50,137,271,350]] as const
const poses = [
  { png: p0, webp: w0 },
  { png: p1, webp: w1 },
  { png: p2, webp: w2 },
  { png: p3, webp: w3 },
  { png: p4, webp: w4 },
  { png: p5, webp: w5 },
  { png: p6, webp: w6 },
  { png: p7, webp: w7 },
  { png: p8, webp: w8 },
  { png: p9, webp: w9 },
] as const
import type { PetPresentation } from '../types'

export const orbPresentation: PetPresentation = {
  id: "orb",
  displayName: {"zh-CN":"光球","en":"Orb"},
  recipe: "pose-sprite",
  packId: "orb-fixture",
  userSelectable: true,
  gradePolicy: {"showExactLevelNumber":false,"showDescription":false,"insigniaMode":"none"},
  gradeLevels: [{"id":"l1","zh-CN":"微光","en":"Spark"},{"id":"l2","zh-CN":"晕光","en":"Glow"},{"id":"l3","zh-CN":"辉光","en":"Shine"},{"id":"l4","zh-CN":"光辉","en":"Radiance"}],
  behavior: {"ambientPool":["rest","look-around","look-left","look-right"],"stateReactions":{"completed":"nod","failed":"shy","working":"nod","needs-input":"peek"},"petting":{"variant":"idle-happy","decoration":"sparkles"}},
  speech: {"idle":[{"zh-CN":"安静地悬浮着，陪你待一会儿。","en":"Floating quietly, keeping you company."},{"zh-CN":"星光很静，我也很静。","en":"The stars are quiet, and so am I."},{"zh-CN":"在呢。","en":"Right here."}],"working":[{"zh-CN":"轨道已校准，开始运转。","en":"Orbit calibrated, spinning up."},{"zh-CN":"光晕全开，专注运转中。","en":"Full halo, focused."}],"needs-input":[{"zh-CN":"轨道上有个问号在等你。","en":"A question mark is waiting in your orbit."},{"zh-CN":"需要你帮个小忙。","en":"Could use a small hand here."}],"completed":[{"zh-CN":"亮了一下，为了你。","en":"That one glowed, just for you."},{"zh-CN":"稳稳入轨，完成。","en":"Smooth orbit. Done."}],"failed":[{"zh-CN":"光环晃了一下，没关系。","en":"The halo wobbled a little. It's okay."},{"zh-CN":"暗一会儿，再亮起来。","en":"Dim for a moment, then bright again."}],"milestone":[{"zh-CN":"又亮了一圈！","en":"Another ring of light!"},{"zh-CN":"轨道更远了，光更稳了。","en":"The orbit widens; the light holds."}],"petting":[{"zh-CN":"光球开心地转了半圈。","en":"The orb spins a happy half-turn."},{"zh-CN":"暖暖的。","en":"Warm."}],"welcome":[{"zh-CN":"你回来啦，星域都亮了。","en":"You're back — the whole sector lit up."}],"ritual":[{"zh-CN":"夜深了，光球调成了小夜灯模式。","en":"Late night; the orb dimmed to night-light mode."}]},
  license: {"license":"Apache-2.0 (code) / CC-BY-4.0 (assets) — see NOTICE and LICENSE.assets","attribution":"Original fixture art generated by the in-repo deterministic pipeline.","provenance":"src/dsh/client/pets/orb/PROVENANCE-orb.json"},
  poseSprite: {
    variantPose: {"idle":0,"idle-happy":1,"idle-curious":2,"idle-sleepy":3,"working":4,"needs-input":5,"completed":6,"completed-proud":7,"failed":8,"cancelled":9},
    poses,
    alphaBounds,
    insignia: undefined,
  },
}
